backend:
  name: git-gateway
  branch: master

media_folder: public/assets
public_folder: /public

collections:
  - label: "Stream Settings"
    name: "Stream Settings"
    files:
      - label: "Stream Settings Entry"
        name: "settings"
        file: "site/settings/streamDetails.json"
        slug: "{{year}}-{{month}}-{{day}}"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Video ID, name: videoId, widget: string}
          - {label: Live, name: category, widget: string}
          - {label: Button Label, name: buttonText, widget: string}