backend:
  name: git-gateway
  branch: master

media_folder: public/assets
public_folder: /public

collections:
  - label: "Stream Settings a"
    name: "Stream Settings b"
    files:
      - label: "Stream Settings c"
        name: "about"
        file: "site/settings/streamDetails.json"
        slug: "{{slug}}"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Video ID, name: videoId, widget: string}
          - {label: Live, name: category, widget: string}
          - {label: Button Label, name: buttonText, widget: string}